### PR TITLE
Replace theme conditionals in templates with new skyIfTheme directive

### PR DESCRIPTION
**Pull request by johnhwhite**
- Replace theme conditionals in templates with new skyIfTheme directive
- Remove SkyThemeService that is no longer needed

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Review by Blackbaud-AlexKingman — COMMENTED** [review]
One question. Looks good!

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-replace-conditionals-with-skyiftheme)

**Pull request merged**
