### PR TITLE
Added inset icon for input box

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-inset-icon](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-inset-icon)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman - the only question I would have (maybe for @Blackbaud-AdamFunderburk) is whether or not clicking on the icon should focus the main section of the input box? Currently nothing happens other than a border flash and the mouse icon when you hover over the icon changes to the standard icon instead of the text cursor that is displayed elsewhere on the input box.

**Comment by Blackbaud-AdamFunderburk** [comment]
> @Blackbaud-AlexKingman - the only question I would have (maybe for @Blackbaud-AdamFunderburk) is whether or not clicking on the icon should focus the main section of the input box? Currently nothing happens other than a border flash and the mouse icon when you hover over the icon changes to the standard icon instead of the text cursor that is displayed elsewhere on the input box.

Yes, it would be correct to focus the input box if the user clicks the icon.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-inset-icon](https://developer.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-inset-icon)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-AlexKingman @Blackbaud-AdamFunderburk 2 final questions:

1. Do we anticipate that there will ever be a scenario where we have inset buttons and an inset icon? We currently do not have a visual example or test of this scenario. Should we?

2. I'd love for @Blackbaud-AdamFunderburk to just double check the mouse icon when hovering over the icon? We now populate the focus back to the input but the mouse icon changes to a standard pointer when you hover the icon instead of the text cursor that is there on the rest of the input box. For a button this would make sense but I'd like him to verify here where the icon is mostly just visual.

**Comment by Blackbaud-AdamFunderburk** [comment]
> @Blackbaud-AlexKingman @Blackbaud-AdamFunderburk 2 final questions:
> 
> 1. Do we anticipate that there will ever be a scenario where we have inset buttons and an inset icon? We currently do not have a visual example or test of this scenario. Should we?
> 2. I'd love for @Blackbaud-AdamFunderburk to just double check the mouse icon when hovering over the icon? We now populate the focus back to the input but the mouse icon changes to a standard pointer when you hover the icon instead of the text cursor that is there on the rest of the input box. For a button this would make sense but I'd like him to verify here where the icon is mostly just visual.

1) I can't think of any scenarios right now, and I can't think of a reason to make an example without a scenario.
2) The cursor behavior is probably fine, as long as the focus gets into the field.

**Review by Blackbaud-TrevorBurch — APPROVED** [review]

**Pull request merged**
