### PR TITLE
Single file attachment

### PR DESCRIPTION
**Pull request by Blackbaud-JackMcElhinney**
Addresses: #22

### CODE REVIEW

**Comment by Blackbaud-JackMcElhinney** [comment]
Here's the behavior of the `@Input`s

`minFileSize` - Works for both versions.
`maxFileSize` - Works for both versions.
`multiple` - **No effect on single file version.**
`validateFn` - Works for both versions.
`acceptedTypes` - Works for both versions.
`noClick` - Works for both versions, though it makes the `Choose File` button un-clickable. Maybe we can change it to `Drag File` when this is enabled.
`allowLinks` - **No effect on single file version.**
`singleFile` - **No effect on default version.**
`required` - Works for both versions.

As for `@Output`s, `filesChanged` emits as it normally would for each, and `linkChanged` will not emit for the single file version.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-JackMcElhinney Would you be willing to spend an hour or two to experiment with a separate component for the single file attachment? Since they are so radically different from a visual and usage standpoint, I'm curious if that would be the better API for our consumers. I'm concerned that having "dead" inputs/outputs for the single file attachment component would cause needless confusion.

If it's possible to somehow use the related features between both components, that would be ideal.

Again, I would only spend a few hours to see if it's feasible. Thanks!

```
<sky-file-attachment>
  <sky-file-attachment-label>
  </sky-file-attachment-label>
</sky-file-attachment>

<sky-file-drop>
  <sky-file-drop-label>
  </sky-file-drop-label>
</sky-file-drop>
```

**Comment by Blackbaud-JackMcElhinney** [comment]
No problem. I'll look into it.

**Comment by Blackbaud-JackMcElhinney** [comment]
Closing in favor of: #57

**Pull request closed without merging**
