### PR TITLE
Added modern styling to select elements in input box

### PR DESCRIPTION
**Pull request by Blackbaud-PaulCrowder**

### CODE REVIEW

**Comment by Blackbaud-AlexKingman** [comment]
In FF, the label and value aren't lined up (see screenshot).

Screen Shot 2020-07-20 at 2 48 06 PM

**Comment by Blackbaud-PaulCrowder** [comment]
> In FF, the label and value aren't lined up (see screenshot).
> 
> Screen Shot 2020-07-20 at 2 48 06 PM

Ah, nice catch. I even tested in Firefox and didn't see that.

**Comment by Blackbaud-AlexKingman** [comment]
Two things...
1. Clicking the select label does not open the dropdown even though it visually seems like it should. Is that a problem?
2. The option value text and the up/down arrows aren't quite vertically centered with each other. This could be a cross-browser nightmare, but should we consider replacing this with a SKY UX icon to get a little more control over how that displays?

**Comment by blackbaud-ado** [comment]
Preview build at [https://host.nxt.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-select](https://host.nxt.blackbaud.com/skyux-forms?_sp.spa=pr-input-box-select)

**Pull request merged**
